apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitbucket
  labels:
    app: bitbucket
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bitbucket
  template:
    metadata:
      labels:
        app: bitbucket
    spec:    
    #      affinity:                                            
    #        podAntiAffinity:                                   
    #          preferredDuringSchedulingIgnoredDuringExecution: 
    #          - weight: 100                                    
    #            podAffinityTerm:                               
    #              labelSelector:                               
    #                matchExpressions:                          
    #                - key: app                                 
    #                  operator: In                             
    #                  values:                                  
    #                  - wordpress                              
    #                  - wordpress-javier                             
    #                  - bamboo                                 
    #                  - nextcloud                              
    #                  key: app.kubernetes.io/instance          
    #                  operator: In                             
    #                  values:                                  
    #                  - jellyfin                               
    #              topologyKey: "kubernetes.io/hostname"        
      hostname: bitbucket
      initContainers:
      - name: change-home-ownership
        image: busybox
        command:
        - chown
        - -R
        - 2003:2003
        - /var/atlassian/application-data/bitbucket/shared
        volumeMounts:
        - name: bitbucket-pv
          mountPath: "/var/atlassian/application-data/bitbucket/shared"
      containers:
      - name: bitbucket
        image: alonsomiguel/arm64v8-bitbucket-server:7.2.3
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 7990
          name: http
        - containerPort: 7999
          name: ssh
        envFrom:
        - configMapRef:
            name: bitbucket-config  
        - secretRef:
            name: server-proxy-name
        - secretRef:
            name: bitbucket-db-user-creds
        volumeMounts:
        - mountPath: "/var/atlassian/application-data/bitbucket/shared"
          name: bitbucket-pv
      nodeSelector:
        k3s.io/hostname: "node04"
      volumes:
      - name: bitbucket-pv
        persistentVolumeClaim:
          claimName: bitbucket-pvc
