apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitbucket-pv
  labels:
    app: bitbucket
spec:
  storageClassName: manual
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - lookupcache=pos
    - noatime
  nfs:
    path: /export/ssd/bitbucket
    server: node06
