apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitbucket-pvc
  labels:
    app: bitbucket
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 32Gi
